POST https://test.api.amadeus.com/v1/security/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=FyEV4kSEgbsfzFAat52AO4KiuYrFFtFg&client_secret=GCRwKFJjVpXRXWAb

###

GET https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=NYC&destinationLocationCode=LAX&departureDate=2024-12-20&adults=1
Authorization: Bearer G30T8ubtisAyFNO6ZhOtl54C7Z7y

###
GET https://restcountries.com/v3.1/all?fields=name,cca2,flags



###
GET https://test.api.amadeus.com/v1/reference-data/locations/hotels/by-city?cityCode=NYC
Authorization: Bearer KbkoRGT9tw0y3c16aqqra91ehllG


###
GET https://test.api.amadeus.com/v3/shopping/hotel-offers?hotelIds=MCLONGHM&adults=1&checkInDate=2024-12-22&paymentPolicy=NONE&roomQuantity=1
Authorization: Bearer B1WD75AcKQO5MsUfA1z4gTRb6nlf


###
GET https://api.geoapify.com/v1/geocode/search?country=US&city=NewYork&apiKey=da6882e372354f72853c683ca0d2f2ce


### 
GET http://localhost:3001/api/hotels?cityCode=ORD&checkInDate=2024-12-25&checkOutDate=2024-12-30


###
GET http://localhost:3001/api/activities?city=Chicago

### 
GET http://localhost:3001/api/hotels?cityCode=NYC&checkInDate=2024-12-25&checkOutDate=2024-12-28
