# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to build and test your project
jobs:
  build:
    docker:
      # Use a Node.js Docker image for the build
      - image: circleci/node:14

    steps:
      # Step 1: Checkout the code
      - checkout

      # Step 2: Navigate to the frontend folder and install dependencies
      - run:
          name: Install dependencies
          working_directory: frontend
          command: |
            npm install

      Step 3: Run tests for the frontend
      - run:
          name: Run frontend tests
          working_directory: frontend
          command: |
            npm test

      Optional: Build the React app
      - run:
          name: Build frontend
          working_directory: frontend
          command: |
            npm run build

      Step 4: Store test results for the frontend (if applicable)
      - store_test_results:
          path: frontend/test-results

  backend-test:
    docker:
      - image: circleci/node:14

    steps:
      # Step 1: Checkout the code
      - checkout

      # Step 2: Navigate to the backend folder and install dependencies
      - run:
          name: Install backend dependencies
          working_directory: backend
          command: |
            npm install

      # Step 3: Run tests for the backend
      - run:
          name: Run backend tests
          working_directory: backend
          command: |
            npm test

      # Step 4: Store test results for the backend (if applicable)
      - store_test_results:
          path: backend/test-results

# Define a workflow to orchestrate the jobs
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - backend-test
